name: Build rtl8812bu

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt update && sudo apt install -y build-essential git wget unzip gcc-arm-linux-gnueabi

      - name: Clone driver
        run: git clone https://github.com/morrownr/88x2bu-20210702.git rtl8812bu

      - name: Build
        run: |
          cd rtl8812bu
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- -C /path/to/openpli/kernel M=$(pwd) modules

      - name: Package IPK
        run: |
          ../ipkg-build.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: rtl8812bu_*.ipk
